services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html   # 新增掛載本地 ./src 到 /var/www/html
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  php-data:
  mysql-data: